name = "alp-website"
account_id = "ef4cff6844394919c511229078a6e9f6"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
main = "./src/server-entry.ts"

routes = [
  { pattern = "alp.anhlp.com", custom_domain = true },
  { pattern = "www.alp.anhlp.com", custom_domain = true },
]

[observability]
enabled = true

[[kv_namespaces]]
binding = "WEBSITE_CACHE"
id = "7a02ccd0f29346379f64d2ab31d1ffb8"
