// alp-rename-keep-file: this module holds the upstream names it maps from.
//
// The one-time paseo → alp rename as a single deterministic function. Every rename of this
// repo and every upstream sync goes through it (see CLAUDE.md § Contract boundaries), so the
// same input always maps to the same output and applying it twice changes nothing.
//
// A text rename has three layers:
//   1. file-level exceptions: LICENSE files, CHANGELOG entries older than 1.0.0, published
//      F-Droid changelogs, the Upstream column of docs/breaking-changes.md, and keep markers;
//   2. protected spans inside a line: upstream URLs and references, Hub-external names, and
//      the Electron browser partition;
//   3. token rules, applied in order to everything outside a protected span.

// Upstream hosts are kept; links into the fork's own repository and domain are renamed with it.
const FORK_REPO_PATH = /^\/phucanh08\/alp(?:[/?#.]|$)/i;
const FORK_DOMAIN = /(?:^|\.)anhlp\.com$/i;
const NETWORK_SCHEMES = new Set([
  "http",
  "https",
  "ssh",
  "git",
  "git+ssh",
  "git+https",
  "ws",
  "wss",
]);
const LOCAL_HOST =
  /^(?:localhost|127(?:\.\d+){3}|0\.0\.0\.0|\[::1?\]|.*\.(?:localhost|invalid|test|example|local|internal)|(?:.*\.)?example\.(?:com|org|net)|(?:.*\.)?my\.domain\.com)$/i;

// Files where the Hub bundle directory `.paseo` is the Hub's name, not the daemon home.
const HUB_BUNDLE_FILES = [
  /^packages\/cli\/src\/commands\/hub\//,
  /^packages\/cli\/tests\/[^/]*hub[^/]*$/,
  /^public-docs\/hub\//,
  /^docs\/hub\.md$/,
];

const KEEP_FILE_MARKER = "alp-rename-keep-file";
const KEEP_LINE_MARKER = /alp-rename-keep(?![\w-])/;
const KEEP_START_MARKER = "alp-rename-keep-start";
const KEEP_END_MARKER = "alp-rename-keep-end";

// Repo-relative files that are regenerated after a rename instead of rewritten as text. Nested
// lockfiles are not regenerated by the root install, so they are rewritten like any other file.
export const REGENERATED_FILES = ["package-lock.json"];

// Token rules, in order. Each rule sees the output of the previous ones.
export const TOKEN_RULES = [
  { id: "npm-scope", pattern: /@getpaseo(?![\w-])/g, replacement: "@alp" },
  { id: "org-name", pattern: /getpaseo/g, replacement: "alp" },
  { id: "bundle-id", pattern: /(?<![\w.-])sh\.paseo(?![\w-])/g, replacement: "com.anhlp.alp" },
  { id: "bundle-id-path", pattern: /(?<![\w.-])sh\/paseo(?=\/)/g, replacement: "com/anhlp/alp" },
  { id: "mcp-prefix", pattern: /mcp__paseo__/g, replacement: "mcp__alp__" },
  { id: "upper", pattern: /PASEO/g, replacement: "ALP" },
  { id: "title", pattern: /Paseo/g, replacement: "Alp" },
  { id: "lower", pattern: /paseo/g, replacement: "alp" },
];

// Protected spans, found per line. `test` is optional: a match only protects when it passes.
export const SPAN_EXCEPTIONS = [
  {
    id: "upstream-url",
    pattern: /(?:\b[a-z][a-z0-9+.-]*:\/\/|\bgit@)[^\s"'`<>()[\]{}|\\,]+/gi,
    test: isUpstreamUrl,
  },
  {
    id: "upstream-org-ref",
    pattern: /(?<![@\w.-])[\w-]+(?:\.[\w-]+)+(?:\\?\/|:)getpaseo(?:(?:\\?\/|%2F)[\w.-]+)?/gi,
  },
  { id: "upstream-org-ref", pattern: /[\w-]+(?:\.[\w-]+)+%2Fgetpaseo(?:%2F[\w.-]+)?/gi },
  { id: "upstream-npm-link", pattern: /npmjs\.(?:com|org)\/(?:package\/)?@getpaseo\/[\w.-]+/gi },
  { id: "upstream-domain", pattern: /(?<![\w.-])(?:[\w-]+\.)*paseo\.(?:sh|cafe)(?![\w-])/gi },
  { id: "electron-partition", pattern: /persist:paseo-browser/g },
  { id: "hub-expression", pattern: /\$\{\{\s*paseo\.[\w.]*/g },
  {
    id: "hub-expression",
    pattern: /(?<![\w$.-])paseo\.(?:prompt|context|inputs|execution)(?:\.\w+)*\b/g,
  },
  { id: "hub-header", pattern: /(?<![\w/-])x-paseo-[\w-]+/gi },
  { id: "hub-bundle", pattern: /\.paseo\/(?:triggers|workflows|hub\.(?:ya?ml|toml))/g },
  {
    id: "hub-bundle",
    pattern: /(?<![\w-])\.paseo(?![\w-])/g,
    appliesTo: (filePath) => HUB_BUNDLE_FILES.some((scope) => scope.test(filePath)),
  },
];

const HIT = /paseo/i;
const WORD = /[\w$@.\-/\\:%]+/g;

function isUpstreamUrl(url) {
  if (!HIT.test(url)) return false;
  let scheme = "git";
  let rest = url;
  const schemeMatch = /^([a-z][a-z0-9+.-]*):\/\/(.*)$/i.exec(url);
  if (schemeMatch) {
    scheme = schemeMatch[1].toLowerCase();
    rest = schemeMatch[2];
  } else {
    rest = url.slice("git@".length);
  }
  if (!NETWORK_SCHEMES.has(scheme)) return false;
  const hostEnd = rest.search(/[/:?#]/);
  const authority = hostEnd === -1 ? rest : rest.slice(0, hostEnd);
  const host = authority.slice(authority.lastIndexOf("@") + 1);
  const pathPart = hostEnd === -1 ? "" : rest.slice(hostEnd).replace(/^:(?!\d)/, "/");
  if (LOCAL_HOST.test(host) || FORK_DOMAIN.test(host)) return false;
  if (/^(?:www\.)?github\.com$/i.test(host) && FORK_REPO_PATH.test(pathPart)) return false;
  return true;
}

export function isLicensePath(filePath) {
  return /^LICEN[CS]E(?:[.-].*)?$/i.test(basename(filePath));
}

// F-Droid shows these as plain text, so they cannot carry a keep marker. Each is written once at
// release time from its CHANGELOG entry, which already went through the rename.
function isFastlaneChangelogPath(filePath) {
  return /^fastlane\/metadata\/android\/[^/]+\/changelogs\/\d+\.txt$/.test(filePath);
}

function basename(filePath) {
  return filePath.slice(filePath.lastIndexOf("/") + 1);
}

function compareVersions(a, b) {
  const pa = a.split(/[.-]/).slice(0, 3).map(Number);
  const pb = b.split(/[.-]/).slice(0, 3).map(Number);
  for (let i = 0; i < 3; i += 1) {
    if (pa[i] !== pb[i]) return pa[i] - pb[i];
  }
  return 0;
}

// Returns, per line, `null` (rename normally), or the rule id that keeps the whole line.
function keptLines(lines, filePath) {
  const kept = Array.from({ length: lines.length }, () => null);
  if (lines.slice(0, 5).some((line) => line.includes(KEEP_FILE_MARKER))) {
    return kept.fill("keep-marker");
  }
  if (isLicensePath(filePath)) {
    return kept.fill("license");
  }
  if (isFastlaneChangelogPath(filePath)) {
    return kept.fill("fastlane-changelog");
  }
  let inRegion = false;
  let inOldChangelogEntry = false;
  const isChangelog = basename(filePath) === "CHANGELOG.md";
  for (let i = 0; i < lines.length; i += 1) {
    const line = lines[i];
    if (line.includes(KEEP_START_MARKER)) inRegion = true;
    if (isChangelog) {
      const heading = /^## \[?v?(\d+\.\d+\.\d+)/.exec(line);
      if (heading) inOldChangelogEntry = compareVersions(heading[1], "1.0.0") < 0;
    }
    if (inRegion || KEEP_LINE_MARKER.test(line)) kept[i] = "keep-marker";
    else if (inOldChangelogEntry) kept[i] = "changelog-before-1.0.0";
    if (line.includes(KEEP_END_MARKER)) inRegion = false;
  }
  return kept;
}

// Character ranges of Markdown table cells in a column headed `Upstream`.
function upstreamColumnSpans(lines, filePath) {
  const spans = new Map();
  if (filePath !== "docs/breaking-changes.md") return spans;
  let column = -1;
  for (let i = 0; i < lines.length; i += 1) {
    const line = lines[i];
    if (!line.trimStart().startsWith("|")) {
      column = -1;
      continue;
    }
    const cells = tableCells(line);
    const next = lines[i + 1] ?? "";
    if (column === -1 && /^\s*\|[\s:|-]+\|\s*$/.test(next)) {
      column = cells.findIndex((cell) => cell.text.trim().toLowerCase() === "upstream");
      continue;
    }
    if (column >= 0 && cells[column]) {
      spans.set(i, [
        { start: cells[column].start, end: cells[column].end, rule: "breaking-changes-upstream" },
      ]);
    }
  }
  return spans;
}

function tableCells(line) {
  const cells = [];
  let start = line.indexOf("|") + 1;
  for (let i = start; i < line.length; i += 1) {
    if (line[i] === "\\") {
      i += 1;
    } else if (line[i] === "|") {
      cells.push({ start, end: i, text: line.slice(start, i) });
      start = i + 1;
    }
  }
  return cells;
}

function protectedSpans(line, filePath, extra) {
  const spans = [...extra];
  for (const exception of SPAN_EXCEPTIONS) {
    if (exception.appliesTo && !exception.appliesTo(filePath)) continue;
    for (const match of line.matchAll(exception.pattern)) {
      const text = match[0].replace(/[.,;:!?]+$/, "");
      if (exception.test && !exception.test(text)) continue;
      spans.push({ start: match.index, end: match.index + text.length, rule: exception.id });
    }
  }
  spans.sort((a, b) => a.start - b.start || b.end - a.end);
  const merged = [];
  for (const span of spans) {
    const last = merged.at(-1);
    if (last && span.start < last.end) {
      last.end = Math.max(last.end, span.end);
    } else {
      merged.push({ ...span });
    }
  }
  return merged;
}

function applyTokenRules(segment) {
  let out = segment;
  for (const rule of TOKEN_RULES) {
    out = out.replace(rule.pattern, rule.replacement);
  }
  return out;
}

function renameSegment(segment, lineNumber, rewrites) {
  if (!HIT.test(segment)) return segment;
  return segment.replace(WORD, (word) => {
    if (!HIT.test(word)) return word;
    const next = applyTokenRules(word);
    if (next !== word) rewrites.push({ line: lineNumber, from: word, to: next });
    return next;
  });
}

/**
 * Renames text content. `path` is the repo-relative path with `/` separators; it selects the
 * file-level exceptions. Returns the new text, every rewrite (line, from, to), and every kept
 * hit (line, rule, text) that still holds `paseo` on purpose.
 */
export function renameText(text, { path: filePath }) {
  const rewrites = [];
  const kept = [];
  if (!HIT.test(text)) return { text, rewrites, kept };
  const lines = text.split("\n");
  const keptByLine = keptLines(lines, filePath);
  const columnSpans = upstreamColumnSpans(lines, filePath);
  const out = lines.map((line, index) => {
    const lineNumber = index + 1;
    if (!HIT.test(line)) return line;
    if (keptByLine[index]) {
      for (const match of line.matchAll(WORD)) {
        if (HIT.test(match[0]))
          kept.push({ line: lineNumber, rule: keptByLine[index], text: match[0] });
      }
      return line;
    }
    const spans = protectedSpans(line, filePath, columnSpans.get(index) ?? []);
    let result = "";
    let cursor = 0;
    for (const span of spans) {
      result += renameSegment(line.slice(cursor, span.start), lineNumber, rewrites);
      const spanText = line.slice(span.start, span.end);
      if (HIT.test(spanText)) kept.push({ line: lineNumber, rule: span.rule, text: spanText });
      result += spanText;
      cursor = span.end;
    }
    result += renameSegment(line.slice(cursor), lineNumber, rewrites);
    return result;
  });
  return { text: out.join("\n"), rewrites, kept };
}

/**
 * Renames a repo-relative path. Every segment goes through the token rules; `sh/paseo`
 * package directories follow the bundle id; the Hub bundle directory `.paseo/<hub dir>` stays.
 */
export function renamePath(filePath) {
  if (!HIT.test(filePath)) return filePath;
  const segments = filePath.split("/");
  const out = [];
  for (let i = 0; i < segments.length; i += 1) {
    const segment = segments[i];
    const next = segments[i + 1];
    if (segment === ".paseo" && /^(?:triggers|workflows|hub\.(?:ya?ml|toml))$/.test(next ?? "")) {
      out.push(segment);
    } else if (segment === "sh" && next === "paseo" && i + 2 < segments.length) {
      out.push("com", "anhlp", "alp");
      i += 1;
    } else {
      out.push(applyTokenRules(segment));
    }
  }
  return out.join("/");
}
